- id: '1579963812582'
  alias: Turn on light in Douglas room
  description: Turns on weekdays at 06:45
  trigger:
  - at: 06:45
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: switch.shelly_douglas_taklampa
    service: switch.turn_on
- id: '1580476587513'
  alias: Turn off light in Douglas room, weekdays
  description: Turns off light in Douglas room weekdays at 8:15
  trigger:
  - at: 08:15
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - entity_id: switch.shelly_douglas_taklampa
    service: switch.turn_off
